export const EVERY_WINE_INFO_REQUEST = 'EVERY_WINE_INFO_REQUEST';
export const EVERY_WINE_INFO_SUCCESS = 'EVERY_WINE_INFO_SUCCESS';
export const EVERY_WINE_INFO_FAILURE = 'EVERY_WINE_INFO_FAILURE';

export const WINE_INFO_BY_IMAGE_REQUEST = 'WINE_INFO_BY_IMAGE_REQUEST';
export const WINE_INFO_BY_IMAGE_SUCCESS = 'WINE_INFO_BY_IMAGE_SUCCESS';
export const WINE_INFO_BY_IMAGE_FAILURE = 'WINE_INFO_BY_IMAGE_FAILURE';

export const LOAD_WINE_INFO_DONE_CHANGE = 'LOAD_WINE_INFO_DONE_CHANGE';
export const WINE_LABEL_NAME_CHANGE = 'WINE_LABEL_NAME_CHANGE';

export const WINE_INFO_BY_KEYWORD_REQUEST = 'WINE_INFO_BY_KEYWORD_REQUEST';
export const WINE_INFO_BY_KEYWORD_SUCCESS = 'WINE_INFO_BY_KEYWORD_SUCCESS';
export const WINE_INFO_BY_KEYWORD_FAILURE = 'WINE_INFO_BY_KEYWORD_FAILURE';

export const WINE_ORDER_BY_ROOM_NUMBER_REQUEST = 'WINE_ORDER_BY_ROOM_NUMBER_REQUEST';
export const WINE_ORDER_BY_ROOM_NUMBER_SUCCESS = 'WINE_ORDER_BY_ROOM_NUMBER_SUCCESS';
export const WINE_ORDER_BY_ROOM_NUMBER_FAILURE = 'WINE_ORDER_BY_ROOM_NUMBER_FAILURE';
