export const WINE_INFO_BY_IMAGE_REQUEST = 'WINE_INFO_BY_IMAGE_REQUEST';
export const WINE_INFO_BY_IMAGE_SUCCESS = 'WINE_INFO_BY_IMAGE_SUCCESS';
export const WINE_INFO_BY_IMAGE_FAILURE = 'WINE_INFO_BY_IMAGE_FAILURE';
export const LOAD_WINE_INFO_DONE_CHANGE = 'LOAD_WINE_INFO_DONE_CHANGE';
